name: Build and Scan

# TODO: トリガーを指定する
on:
  push:
    branches: [ todo ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Java (今回アプリケーションを作る言語) を使えるようにする
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    # JFrog　CLIを使えるようにする
    - name: Set up JFrog CLI
      uses: jfrog/setup-jfrog-cli@v2

    # TODO: アプリケーションをテスト・ビルドし、Artifactoryにプッシュする
    - name: Build and publish the application
      run: |
        ./gradlew bootJar

    # TODO: 脆弱性のスキャンを行う
    - name: Scan artifacts
